In [118]:
import csv
import pandas as pd
DROPBOX_PATH = '/Users/tejav/Dropbox/Data_Int_Fin_Class/rawdata/fx/'

In [119]:
# barclays spot

barclays_spot_83 = pd.read_csv(DROPBOX_PATH + 'barclays_spot_83.csv', skiprows=range(1, 2))
barclays_spot_93 = pd.read_csv(DROPBOX_PATH + 'barclays_spot_93.csv', skiprows=range(1, 2))
barclays_spot_03 = pd.read_csv(DROPBOX_PATH + 'barclays_spot_03.csv', skiprows=range(1, 2))
barclays_spot_09 = pd.read_csv(DROPBOX_PATH + 'barclays_spot_09.csv', skiprows=range(1, 2))

In [120]:
barclays_spot_83.rename(columns={'#ERROR':'EURO TO US $ 1M FWD (BBI) - EXCHANGE RATE'}, inplace=True)

In [121]:
barclays_spot = pd.concat([barclays_spot_83, barclays_spot_93, barclays_spot_03, barclays_spot_09]).drop(columns=['#ERROR'])

In [122]:
barclays_spot_clean = barclays_spot.dropna(axis=0, thresh=0.3*barclays_spot.shape[1])

In [123]:
from datetime import date, timedelta

barclays_spot_clean['Date'] = barclays_spot_clean['Name'].apply(lambda x: date(1900,1,1) + timedelta((int)(x)))
barclays_spot_clean = barclays_spot_clean.set_index('Date')

<ipython-input-123-ab1b1017184e>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  barclays_spot_clean['Date'] = barclays_spot_clean['Name'].apply(lambda x: date(1900,1,1) + timedelta((int)(x)))

In [126]:
# invert US to UK exchange rate as that is the only one inverted
barclays_spot_clean['US $ TO UK Â£ (BBI) - EXCHANGE RATE'] = 1.0/barclays_spot_clean['US $ TO UK Â£ (BBI) - EXCHANGE RATE']
barclays_spot_clean

,Name,US $ TO UK Â£ (BBI) - EXCHANGE RATE,ITALIAN LIRA TO US $ (BBI) - EXCHANGE RATE,BELGIAN FR.TO US $ SPT FN(BBI) DISC - EXCHANGE RATE,FRENCH FRANC TO US $ (BBI) - EXCHANGE RATE,SWISS FRANC TO US $ (BBI) - EXCHANGE RATE,GERMAN MARK TO US $ (BBI) - EXCHANGE RATE,NETH. GUILDER TO US $ (BBI) - EXCHANGE RATE,JAPANESE YEN TO US $ (BBI) - EXCHANGE RATE,HONG KONG $ TO US $ (BBI) - EXCHANGE RATE,...,CANADIAN $ TO US $ (BBI) - EXCHANGE RATE,SINGAPORE $ TO US $ (BBI) - EXCHANGE RATE,MALAYSIAN RINGGIT TO US $ (BBI) DISC - EXCHANGE RATE,AUSTRALIAN $ TO US $ (BBI) - EXCHANGE RATE,NEW ZEALAND $ TO US $ (BBI) - EXCHANGE RATE,SWEDISH KRONA TO US $ (BBI) - EXCHANGE RATE,NORWEGIAN KRONE TO US $ (BBI - EXCHANGE RATE,DANISH KRONE TO US $ (BBI) - EXCHANGE RATE,EURO TO US $ 1M FWD (BBI) - EXCHANGE RATE,EURO TO US $ (BBI) - EXCHANGE RATE
Date,,,,,,,,,,,,,,,,,,,,,
1983-10-13,30600.0,0.661244,1572.50,52.65,7.9225,2.0995,2.5830,2.8972,232.325,8.3450,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1983-10-14,30601.0,0.661244,1572.50,52.65,7.9225,2.0995,2.5830,2.8972,232.325,8.3450,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1983-10-15,30602.0,0.666223,1581.50,52.94,7.9635,2.1142,2.6035,2.9177,232.955,8.2450,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1983-10-16,30603.0,0.666889,1587.50,53.26,7.9900,2.1202,2.6175,2.9300,232.925,8.1750,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1983-10-19,30606.0,0.666889,1580.50,53.03,7.9535,2.1102,2.6020,2.9160,232.900,8.0250,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2021-08-18,44424.0,0.722230,1644.18,NaN,5.5701,0.9123,1.6608,1.8713,109.244,7.7843,...,1.2575,1.3555,NaN,1.3633,1.4261,8.6513,8.8323,6.3144,NaN,0.84915
2021-08-19,44425.0,0.728173,1653.08,NaN,5.6002,0.9144,1.6698,1.8814,109.551,7.7923,...,1.2642,1.3627,NaN,1.3798,1.4484,8.7601,8.9167,6.3490,NaN,0.85374
2021-08-20,44426.0,0.726586,1652.88,NaN,5.5995,0.9165,1.6696,1.8812,109.851,7.7868,...,1.2634,1.3599,NaN,1.3799,1.4503,8.7212,8.8913,6.3484,NaN,0.85364
2021-08-21,44427.0,0.732654,1657.72,NaN,5.6159,0.9181,1.6745,1.8867,109.813,7.7893,...,1.2808,1.3646,NaN,1.3974,1.4632,8.7979,9.0285,6.3669,NaN,0.85614
2021-08-22,44428.0,0.733891,1655.28,NaN,5.6077,0.9174,1.6720,1.8839,109.845,7.7891,...,1.2839,1.3619,NaN,1.4011,1.4637,8.8051,9.0273,6.3574,NaN,0.85488

In [67]:
# barclays forward

barclays_forward_83 = pd.read_csv(DROPBOX_PATH + 'barclays_forward_83.csv', skiprows=range(1, 2))
barclays_forward_93 = pd.read_csv(DROPBOX_PATH + 'barclays_forward_93.csv', skiprows=range(1, 2))
barclays_forward_03 = pd.read_csv(DROPBOX_PATH + 'barclays_forward_03.csv', skiprows=range(1, 2))
barclays_forward_09 = pd.read_csv(DROPBOX_PATH + 'barclays_forward_09.csv', skiprows=range(1, 2))

In [68]:
# total rows
barclays_forward_83.shape[0] + barclays_forward_93.shape[0] + barclays_forward_03.shape[0] + barclays_forward_09.shape[0]

10084

In [69]:
barclays_forward_83.rename(columns={'#ERROR':'EURO TO US $ 1M FWD (BBI) - EXCHANGE RATE'}, inplace=True)

In [70]:
barclays_forward = pd.concat([barclays_forward_83, barclays_forward_93, barclays_forward_03, barclays_forward_09]).drop(columns=['#ERROR', '#ERROR.1', '#ERROR.2', '#ERROR.3', '#ERROR.4', '#ERROR.5'])

In [71]:
barclays_forward_clean = barclays_forward.dropna(axis=0, thresh=0.3*barclays_forward.shape[1])

In [75]:
from datetime import date, timedelta

barclays_forward_clean['Date'] = barclays_forward_clean['Name'].apply(lambda x: date(1900,1,1) + timedelta((int)(x)))

<ipython-input-75-de0aa9051dc9>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  barclays_forward_clean['Date'] = barclays_forward_clean['Name'].apply(lambda x: date(1900,1,1) + timedelta((int)(x)))

In [77]:
barclays_forward_clean = barclays_forward_clean.set_index('Date')

In [127]:
barclays_forward_clean['US $ TO UK Â£ 1M FWD (BBI) - EXCHANGE RATE'] = 1.0/barclays_forward_clean['US $ TO UK Â£ 1M FWD (BBI) - EXCHANGE RATE']
barclays_forward_clean

,Name,US $ TO UK Â£ 1M FWD (BBI) - EXCHANGE RATE,ITL.LIRA TO US $ 1M FWD (BBI) DISC - EXCHANGE RATE,BELGIAN FR.TO US $ 1MF FN(BBI) DISC - EXCHANGE RATE,FRENCH FR. TO US $ 1M FWD(BBI) DISC - EXCHANGE RATE,CHF TO US$ 1M FWD (BBI) DISC - EXCHANGE RATE,GERMAN MARK TO US $ 1M FWD(BBI) DISC - EXCHANGE RATE,NETH. GUILDER TO US $ 1MFWD(BBI)DISC - EXCHANGE RATE,JPY TO US$ 1M FWD (BBI) DISC - EXCHANGE RATE,HONG KONG $ TO US $ 1M FWD (BBI) - EXCHANGE RATE,SOUTH AFRICA RAND TO US $ 1M FWD(BBI) - EXCHANGE RATE,CANADIAN $ TO US $ 1M FWD (BBI) - EXCHANGE RATE,SINGAPORE $ TO US $ 1M FWD (BBI) - EXCHANGE RATE,MALAYSIAN RGT. TO US $ 1M (BBI)DISC' - EXCHANGE RATE,AUD$ TO US$ 1M FWD (BBI) DISC - EXCHANGE RATE,NZD TO US$ 1M FWD (BBI) DISC - EXCHANGE RATE,SEK TO US$ 1M FWD (BBI) DISC - EXCHANGE RATE,NOK TO US$ 1M FWD (BBI) DISC - EXCHANGE RATE,DKK TO US $ 1M FWD (BBI) DISC - EXCHANGE RATE,EURO TO US $ 1M FWD (BBI) - EXCHANGE RATE
Date,,,,,,,,,,,,,,,,,,,,
1983-10-13,30600.0,0.661070,NaN,52.63,7.9477,2.0883,2.5740,2.8882,231.690,8.9450,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1983-10-14,30601.0,0.661070,NaN,52.63,7.9477,2.0883,2.5740,2.8882,231.690,8.9450,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1983-10-15,30602.0,0.666001,NaN,52.90,7.9852,2.1034,2.5945,2.9087,232.325,8.6450,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1983-10-16,30603.0,0.666622,NaN,53.24,8.0125,2.1091,2.6083,2.9210,232.320,8.5750,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1983-10-19,30606.0,0.666756,NaN,52.99,7.9762,2.0989,2.5925,2.9066,232.270,8.5750,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2021-08-18,44424.0,0.722178,NaN,NaN,NaN,0.9945,NaN,NaN,110.400,7.7838,14.8922,1.2576,1.3556,NaN,1.3698,1.5153,9.128,8.3636,6.5312,0.84862
2021-08-19,44425.0,0.728120,NaN,NaN,NaN,0.9945,NaN,NaN,110.400,7.7920,14.9677,1.2642,1.3628,NaN,1.3698,1.5153,9.128,8.3636,6.5312,0.85323
2021-08-20,44426.0,0.726533,NaN,NaN,NaN,0.9945,NaN,NaN,110.400,7.7864,14.9922,1.2635,1.3600,NaN,1.3698,1.5153,9.128,8.3636,6.5312,0.85314
2021-08-21,44427.0,0.732601,NaN,NaN,NaN,0.9945,NaN,NaN,110.400,7.7888,15.2920,1.2808,1.3647,NaN,1.3698,1.5153,9.128,8.3636,6.5312,0.85564
2021-08-22,44428.0,0.733837,NaN,NaN,NaN,0.9945,NaN,NaN,110.400,7.7886,15.4198,1.2840,1.3620,NaN,1.3698,1.5153,9.128,8.3636,6.5312,0.85438

In [137]:
## reuters data

reuters_pre_2008_spot = pd.read_csv(DROPBOX_PATH + 'reuters_spot_pre_2008.csv', skiprows=range(1, 2))
reuters_post_2008_spot = pd.read_csv(DROPBOX_PATH + 'reuters_spot_post_2008.csv', skiprows=range(1, 2))
reuters_spot = pd.concat([reuters_pre_2008_spot, reuters_post_2008_spot])

In [138]:
reuters_spot['Date'] = reuters_spot['Name'].apply(lambda x: date(1900,1,1) + timedelta((int)(x)))
reuters_spot = reuters_spot.set_index('Date')

In [139]:
reuters_spot

,Name,ALBANIAN LEK TO US $ (WMR) - EXCHANGE RATE,ALGERIAN DINAR TO US $ (WMR) - EXCHANGE RATE,ARGENTINE PESO TO US $ (WMR) - EXCHANGE RATE,US $ TO AUSTRALIAN $ (WMR) - EXCHANGE RATE,AUSTRIAN SCHIL.TO US $ (WMR) - EXCHANGE RATE,BAHRAINI DINAR TO US $ (WMR) - EXCHANGE RATE,BANGLADESH TAKA TO US $ (WMR) - EXCHANGE RATE,BELGIAN FRANC TO US $ (WMR) - EXCHANGE RATE,BERMUDA $ TO US $ (WMR) - EXCHANGE RATE,...,VANUATU VATU TO US $ (WMR) - EXCHANGE RATE,VENEZ. BOLIVAR F. TO US $ (WMR) - EXCHANGE RATE,VIETNAMESE DONG TO US $ (WMR) - EXCHANGE RATE,ZAMBIAN KWACHA TO US $ (WMR) - EXCHANGE RATE,NEW ZIMBABWE $ TO US $ (WMR) - EXCHANGE RATE,US $ TO UK Â£ (WMR) - EXCHANGE RATE,MAURITANIAN OUGUYIA TO US $(WMR)DISC - EXCHANGE RATE,PERUVIAN SOL TO US $ (WMR) - EXCHANGE RATE,VENEZ. BOLIVAR F. TO US $ (WMR)DISC - EXCHANGE RATE,ZAMBIAN KWACHA (R) TO US $ (WMR) - EXCHANGE RATE
Date,,,,,,,,,,,,,,,,,,,,,
1997-01-02,35430.0,NaN,NaN,0.99980,0.79430,10.83950,0.37700,42.450,31.7645,1.0,...,110.900,0.47625,NaN,NaN,NaN,1.71130,NaN,NaN,NaN,NaN
1997-01-03,35431.0,NaN,NaN,0.99980,0.79430,10.83950,0.37700,42.450,31.7645,1.0,...,110.900,0.47625,NaN,NaN,NaN,1.71130,NaN,NaN,NaN,NaN
1997-01-04,35432.0,NaN,NaN,0.99980,0.78990,10.84810,0.37700,42.450,31.7650,1.0,...,110.900,0.47622,NaN,NaN,NaN,1.69080,NaN,NaN,NaN,NaN
1997-01-05,35433.0,NaN,NaN,0.99950,0.79160,10.95760,0.37700,42.450,32.0870,1.0,...,110.900,0.47625,NaN,NaN,NaN,1.69180,NaN,NaN,NaN,NaN
1997-01-08,35436.0,NaN,NaN,0.99990,0.78830,11.01000,0.37700,42.450,32.2275,1.0,...,110.900,0.47650,NaN,NaN,NaN,1.68470,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2021-08-18,44424.0,102.970,135.260,97.02290,0.73365,11.67265,0.37705,84.870,34.2198,1.0,...,111.945,NaN,22835.0,NaN,85.7467,1.38605,357.3,4.07735,248520.96,19.175
2021-08-19,44425.0,103.605,135.370,97.23460,0.72575,11.74440,0.37705,84.940,34.4300,1.0,...,111.865,NaN,22832.5,NaN,85.7467,1.37380,357.3,4.09100,248520.96,19.153
2021-08-20,44426.0,103.755,135.395,97.26795,0.72370,11.74940,0.37705,84.960,34.4447,1.0,...,112.705,NaN,22808.5,NaN,85.8290,1.37570,357.3,4.09420,248520.96,18.625
2021-08-21,44427.0,104.225,135.430,97.28435,0.71565,11.77855,0.37700,85.125,34.5302,1.0,...,112.895,NaN,22816.5,NaN,85.8290,1.36610,357.3,4.09750,248520.96,17.525
2021-08-22,44428.0,104.205,135.430,97.31845,0.71260,11.78160,0.37705,85.125,34.5391,1.0,...,113.635,NaN,22825.0,NaN,85.8290,1.36150,357.3,4.11230,248520.96,17.025

In [140]:
# invert anything that starts with US in column
for column in reuters_spot.columns:
    if column[:2] == 'US':
        reuters_spot[column] = 1.0/reuters_spot[column]

In [141]:
## reuters data

reuters_pre_2008_forward = pd.read_csv(DROPBOX_PATH + 'reuters_forward_pre_2008.csv', skiprows=range(1,2))
reuters_post_2008_forward = pd.read_csv(DROPBOX_PATH + 'reuters_forward_post_2008.csv', skiprows=range(1, 2))
reuters_forward = pd.concat([reuters_pre_2008_forward, reuters_post_2008_forward])

In [142]:
reuters_forward['Date'] = reuters_forward['Name'].apply(lambda x: date(1900,1,1) + timedelta((int)(x)))
reuters_forward = reuters_forward.set_index('Date')

In [143]:
# invert anything that starts with US in column
for column in reuters_forward.columns:
    if column[:2] == 'US':
        reuters_forward[column] = 1.0/reuters_forward[column]